# Generated by Django 6.0.5 on 2026-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_quota_and_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mail Hesabı', 'verbose_name_plural': 'Mail Hesapları'},
        ),
        migrations.AlterModelOptions(
            name='maildomain',
            options={'ordering': ['name']},
        ),
    ]
