# Generated by Django 5.2.1 on 2026-05-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mailaccount_id_alter_maildomain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='auto_responder_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='auto_responder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='auto_responder_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='forward_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='forward_to',
            field=models.EmailField(blank=True, default='', help_text='Yönlendirme adresi', max_length=254),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='keep_copy',
            field=models.BooleanField(default=True, help_text='Yönlendirme yaparken kopyayı sakla'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Email imzası'),
        ),
    ]
