# Generated by Django 5.2.1 on 2026-05-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='dkim_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='dkim_private_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='dkim_public_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='dkim_record',
            field=models.CharField(blank=True, default='', max_length=510),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='dmarc_record',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='spf_record',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('verified', 'Doğrulanmış'), ('failed', 'Başarısız')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
