# Generated by Django 5.2.1 on 2026-05-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_domain_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('full', 'Tam Yedekleme'), ('incremental', 'Artımlı Yedekleme'), ('config', 'Konfigürasyon'), ('emails', 'E-postalar')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_size_mb', models.FloatField(default=0)),
                ('includes_emails', models.BooleanField(default=False)),
                ('includes_configs', models.BooleanField(default=False)),
                ('includes_database', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_auto_backup', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Yedekleme',
                'verbose_name_plural': 'Yedeklemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
