# Generated by Django 5.2.1 on 2026-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_backup_id_alter_mailaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildomain',
            name='dns_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Provider API token/secret (encrypted-at-rest önerilir)'),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='dns_provider',
            field=models.CharField(choices=[('manual', 'Manuel'), ('cloudflare', 'Cloudflare'), ('route53', 'AWS Route53'), ('namecheap', 'Namecheap')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='tls_cert_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='tls_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='tls_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maildomain',
            name='tls_key_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
