# Generated by Django 5.2.1 on 2026-05-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_maildomain_dns_credentials_maildomain_dns_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('uidvalidity', models.BigIntegerField(default=0)),
                ('uidnext', models.BigIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('unread', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.mailaccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MailMessageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('from_addr', models.CharField(blank=True, default='', max_length=500)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_addr', models.TextField(blank=True, default='')),
                ('cc_addr', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('is_seen', models.BooleanField(db_index=True, default=False)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('snippet', models.CharField(blank=True, default='', max_length=500)),
                ('raw_size', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webmail.mailfolder')),
            ],
            options={
                'ordering': ['-date', '-uid'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachmentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='webmail.mailmessagecache')),
            ],
            options={
                'ordering': ['part_id'],
            },
        ),
        migrations.AddIndex(
            model_name='mailmessagecache',
            index=models.Index(fields=['folder', '-date'], name='webmail_mai_folder__ff5dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessagecache',
            index=models.Index(fields=['folder', '-uid'], name='webmail_mai_folder__d5a63c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailmessagecache',
            unique_together={('folder', 'uid')},
        ),
    ]
