# Generated by Django 5.2.1 on 2026-05-13 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Kurulum Çalışması',
                'verbose_name_plural': 'Kurulum Çalışmaları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('skipped', 'Atlandı')], default='pending', max_length=20)),
                ('log', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='installer.installationrun')),
            ],
            options={
                'verbose_name': 'Kurulum Adımı',
                'verbose_name_plural': 'Kurulum Adımları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
