# Dovecot SQL Passdb Configuration for Jîr-Mail
# Bu dosyayı /etc/dovecot/dovecot-sql.conf olarak kaydet

driver = pgsql
connect = host=82.153.241.171 port=5432 dbname=jir_mail_prod user=postgres password=YwzYYQkUjO29REPbignRwVVyJnM3r8cBg5h7NE7kyvc0wMYg99Ccf5mGPMnpuig1
default_pass_scheme = BLF-CRYPT
password_query = SELECT email as user, password_hash AS password, 'maildir:/var/mail/vhosts/%d/%n' AS userdb_home, 'maildir:/var/mail/vhosts/%d/%n' AS mail, 5000 AS uid, 5000 AS gid FROM core_mailaccount WHERE email = '%u' AND is_active = true

# Optional: debug için
# log_path = /var/log/dovecot-sql.log