"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r%36n))g&hrl-di8^5$ni9(j5y@ovwju!(1q)ql*^%#9emwh_w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'management',
    'saas',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
        'CONN_MAX_AGE': 0,
        'OPTIONS': {},
    }
}

# Check for persisted DB config first
_db_config_path = BASE_DIR / 'config' / 'db_config.json'
if _db_config_path.exists():
    try:
        import json
        with open(_db_config_path) as f:
            _db_conf = json.load(f)
        _db_conf.setdefault('ATOMIC_REQUESTS', False)
        _db_conf.setdefault('AUTOCOMMIT', True)
        _db_conf.setdefault('CONN_MAX_AGE', 600)
        _db_conf.setdefault('OPTIONS', {})
        DATABASES['default'] = _db_conf
    except Exception:
        pass
else:
    # Try to use PostgreSQL if available
    _db_url = os.getenv('DATABASE_URL', '')
    if _db_url:
        try:
            import psycopg2
            parsed = urlparse(_db_url)
            conn = psycopg2.connect(
                host=parsed.hostname,
                port=parsed.port or 5432,
                user=parsed.username,
                password=parsed.password,
                database=parsed.path.lstrip('/'),
                connect_timeout=3
            )
            conn.close()
            _db_conf = dj_database_url.config(default=_db_url, conn_max_age=600)
            _db_conf.setdefault('ATOMIC_REQUESTS', False)
            _db_conf.setdefault('AUTOCOMMIT', True)
            _db_conf.setdefault('OPTIONS', {})
            DATABASES['default'] = _db_conf
        except Exception:
            pass

def is_jir_installed():
    try:
        from django.db import connection
        connection.ensure_connection()
        from saas.models import SystemConfig
        config = SystemConfig.objects.first()
        return config.is_installed if config else False
    except Exception:
        return False

def get_jir_local_key():
    try:
        from django.db import connection
        connection.ensure_connection()
        from saas.models import SystemConfig
        config = SystemConfig.objects.first()
        if config and config.jir_local_key:
            return config.jir_local_key
    except Exception:
        pass
    return os.getenv('JIR_LOCAL_KEY', 'JirCode_Alpha_2026_Secure_Key_v1')

# Lazy initialization - defaults until DB is ready
IS_INSTALLED = False
JIR_LOCAL_KEY = os.getenv('JIR_LOCAL_KEY', 'JirCode_Alpha_2026_Secure_Key_v1')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

POSTFIX_VMAIL_PATH = os.getenv('POSTFIX_VMAIL_PATH', '/etc/postfix/vmail_accounts')
POSTFIX_VMAIL_HOME = os.getenv('POSTFIX_VMAIL_HOME', '/var/mail/vhosts')
DOVECOT_PASSDB_PATH = os.getenv('DOVECOT_PASSDB_PATH', '/etc/dovecot/userdb')
