# Generated by Django 6.0.5 on 2026-05-08 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('hq_verified', models.BooleanField(default=False)),
                ('hq_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(choices=[('FREE', 'Free (3 Accounts)'), ('PRO', 'Pro (50 Accounts)'), ('ENT', 'Enterprise (Unlimited)')], default='FREE', max_length=10)),
                ('max_accounts', models.PositiveIntegerField(default=3)),
                ('storage_limit_gb', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
