# Generated by Django 6.0.5 on 2026-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='jir_local_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
