# Generated by Django 5.2.1 on 2026-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_systemconfig_jir_local_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
