# Generated by Django 5.2.1 on 2026-05-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_alter_systemconfig_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('error', 'Hata'), ('critical', 'Kritik')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('system', 'Sistem'), ('disk', 'Disk'), ('memory', 'Bellek'), ('cpu', 'CPU'), ('database', 'Veritabanı'), ('mail', 'Mail Servisi'), ('security', 'Güvenlik'), ('backup', 'Yedekleme')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('threshold_value', models.CharField(blank=True, default='', max_length=50)),
                ('current_value', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Uyarı',
                'verbose_name_plural': 'Uyarılar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric', models.CharField(choices=[('disk_usage', 'Disk Kullanımı %'), ('memory_usage', 'Bellek Kullanımı %'), ('cpu_usage', 'CPU Kullanımı %'), ('mail_queue', 'Mail Kuyruğu'), ('failed_logins', 'Başarısız Girişler'), ('storage_quota', 'Depolama Kotası %')], max_length=30)),
                ('warning_threshold', models.FloatField(default=70.0)),
                ('critical_threshold', models.FloatField(default=90.0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('check_interval_minutes', models.PositiveIntegerField(default=5)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Uyarı Eşiği',
                'verbose_name_plural': 'Uyarı Eşikleri',
                'ordering': ['metric'],
            },
        ),
    ]
