# Generated by Django 5.2.1 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_alert_alertthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='backup_dir',
            field=models.CharField(blank=True, default='/var/backups/jirmail', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_engine',
            field=models.CharField(choices=[('django.db.backends.sqlite3', 'SQLite'), ('django.db.backends.postgresql', 'PostgreSQL')], default='django.db.backends.sqlite3', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_host',
            field=models.CharField(blank=True, default='localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_port',
            field=models.PositiveIntegerField(blank=True, default=5432, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='db_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='dovecot_passdb_path',
            field=models.CharField(blank=True, default='/etc/dovecot/userdb', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='mail_data_path',
            field=models.CharField(blank=True, default='/var/mail/vhosts', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='postfix_vmail_path',
            field=models.CharField(blank=True, default='/etc/postfix/vmail_accounts', max_length=500),
        ),
    ]
