# Generated by Django 5.2.1 on 2026-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_alter_alert_id_alter_alertthreshold_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='installation_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
